apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  creationTimestamp: null
  labels:
    io.kompose.service: movie-service-claim0
  name: movie-service-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: qa
  creationTimestamp: null
  labels:
    io.kompose.service: movie-service-claim0
  name: movie-service-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: staging
  creationTimestamp: null
  labels:
    io.kompose.service: movie-service-claim0
  name: movie-service-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prod
  creationTimestamp: null
  labels:
    io.kompose.service: movie-service-claim0
  name: movie-service-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
